#!/bin/sh

shed_pid="${$}"

SHED_ENV_EXPORT_LOC=""
SHED_RELOAD=""

# check if GUI_SESSION_PID is set
if [ -n "$GUI_SESSION_PID" ]; then
  # since it exists that will be the SHED_SESSION_PID
  export SHED_SESSION_PID="$GUI_SESSION_PID"
else
  if [ -z "$SHED_SESSION_PID" ]; then
    # it wasnt set, so we will use the shed_pid
    export SHED_SESSION_PID="$shed_pid"
  fi
fi

# cuz $UID is not POSIX ¯\_(ツ)_/¯
# but it may be defined in the environment
if [ -z "$UID" ]; then
  # result of: id -u $USER
  UserID=$(id -u "$USER")
else
  UserID="$UID"
fi

# define XDG_RUNTIME_DIR if it doesn't exist
if [ -z "${XDG_RUNTIME_DIR}" ]; then
  # test if the usual location is writeable
  if [ -w "/run/user/${UserID}" ]; then
    # we can simply export it now
    export XDG_RUNTIME_DIR="/run/user/${UserID}"
  else
    # welp, gotta define it as something
    export XDG_RUNTIME_DIR=/tmp/"${UserID}"-runtime-dir
    if ! test -d "${XDG_RUNTIME_DIR}"; then
      mkdir "${XDG_RUNTIME_DIR}"
      chmod 0700 "${XDG_RUNTIME_DIR}"
    fi
  fi
fi

# should return shed's cgroup, cgroup is a linux only feature tho
get_shed_cgroup() {
  # so we can just wing it and use /proc/ directly
  sed 's@.*::/@@' /proc/"${shed_pid}"/cgroup
}

# do we got an XDG_SESSION_ID ?
if [ -z "$XDG_SESSION_ID" ]; then
  # okay, since we don't it will be shed's cgroup
  # other kernels like the bsd families, illumos, darwin, etc ought to have
  # something similar-ish or some property that gets assigned to processes and
  # propagated to their children that we can get and use to define an
  # XDG_SESSION_ID, at least i know bsd got the jails system but got no idea if
  # that would be the correct property to use for this, no idea if people in
  # other unices and unix-like os even care about something like shed to begin
  # with as i'd assume they already got something better and is just we linux
  # folk whom are stuck in the obscurantism of systemd...
  XDG_SESSION_ID="$(get_shed_cgroup)"
  export XDG_SESSION_ID
fi

set_xdg_desktop_vars=""
session_desktop=""
current_desktop=""
use_xdg_session_type=""
set_xdg_home_dirs=""

if [ -z "$XDG_CONFIG_HOME" ]; then
  export XDG_CONFIG_HOME="${HOME}/.config"
fi

old_conf_dir="${XDG_CONFIG_HOME:-${HOME}/.config}/shed/conf"
# directory where we are loading the shed specific config
ConfDir="${XDG_CONFIG_HOME:-${HOME}/.config}/shed"
if [ -d "$old_conf_dir" ]; then
  ConfDir="$old_conf_dir"
fi
# shed config file
# ${XDG_CONFIG_HOME:-${HOME}/.config}/shed/shed.rc
Config="${ConfDir}/shed.rc"
# the default config template
DefConf="@DOC@/shed.rc"

if [ -r "$Config" ]; then
  . "$Config"
else
  cp "$DefConf" "$Config"
fi

if [ -n "$set_xdg_desktop_vars" ]; then
  export XDG_SESSION_DESKTOP="$session_desktop"
  export XDG_CURRENT_DESKTOP="$current_desktop"
fi

if [ -n "$use_xdg_session_type" ]; then
  export XDG_SESSION_TYPE="$use_xdg_session_type"
fi

if [ -n "$set_xdg_home_dirs" ]; then
  if [ -z "$XDG_DATA_HOME" ]; then
    export XDG_DATA_HOME="$HOME/.local/share"
  fi
  if [ -z "$XDG_CACHE_HOME" ]; then
    export XDG_CACHE_HOME="$HOME/.cache"
  fi
  if [ -z "$XDG_STATE_HOME" ]; then
    export XDG_STATE_HOME="$HOME/.local/state"
  fi
  if [ ! -f "$XDG_CONFIG_HOME/user-dirs.dirs" ]; then
    xdg-user-dirs-update
  fi
  . "$XDG_CONFIG_HOME/user-dirs.dirs"
  export XDG_DESKTOP_DIR
  export XDG_DOWNLOAD_DIR
  export XDG_TEMPLATES_DIR
  export XDG_PUBLICSHARE_DIR
  export XDG_DOCUMENTS_DIR
  export XDG_MUSIC_DIR
  export XDG_PICTURES_DIR
  export XDG_VIDEOS_DIR
fi

if [ -n "$SHED_ENV_EXPORT_LOC" ]; then
  env_export_dir="${SHED_ENV_EXPORT_LOC%/*}"
  if [ ! -d "$env_export_dir" ]; then
    mkdir -p "$env_export_dir"
  fi
  cat << __ENV_EXPORT__ >> "$SHED_ENV_EXPORT_LOC"
export XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR"
export XDG_SESSION_ID="$XDG_SESSION_ID"
export SHED_SESSION_PID="$SHED_SESSION_PID"
__ENV_EXPORT__
fi

# source shed library
. ./libshed.sh

# shed
# --------------------------
# the SHell Execution Daemon
prog="${0##*/}"

# werether or not the ShedSessionDir was present at startup
# initial value: $_false
sessdir="$_false"

# werether shed is a fresh start or a post reload
# default: $_false
reloaded="$_false"

# check if the session dir exists
if [ -d "$ShedSessionDir" ]; then
  # let the program knows the dir exists
  sessdir="$_true"
else
  # create the session dir if it doesn't exist
  mkdir -p "$ShedSessionDir"
fi

if [ ! -d "$shed_service_pid_dir" ]; then
  mkdir -p "$shed_service_pid_dir"
fi
if [ ! -d "$shed_component_pid_dir" ]; then
  mkdir -p "$shed_component_pid_dir"
fi
if [ ! -d "$shed_logs_dir" ]; then
  mkdir -p "$shed_logs_dir"
fi

# create the socket file if necessary
if [ ! -p "$msg_socket" ]; then
  if [ -f "$msg_socket" ]; then
    rm "$msg_socket"
  fi
  mkfifo -m 600 "$msg_socket"
fi

# create the empty reply file if necessary
if [ -f "$msg_reply" ]; then
  : > "$msg_reply"
fi


# shallow execution routine
if [ "$sessdir" -eq "$_false" ]; then
  if ! is_dir_empty "$ShallowEnvDir"; then
    for EnvFile in "$ShallowEnvDir"/*.env; do
      if [ -r "$EnvFile" ]; then
        msg_log "info" "loading env file $EnvFile"
        . "$EnvFile"
      fi
    done
    unset EnvFile
  fi
  # exec transient
  if [ -x "$UseTransient" ]; then
    msg_log "info" "shed-shallow executing $UseTransient"
    exec "$UseTransient"
  else
    msg_log "info" "shed-shallow executing $0"
    exec "$0"
  fi
fi

# check if shed is reloading, writing to socket is not possible when starting
# on a fresh session cuz no one is listening to the socket
if [ "$sessdir" -eq "$_true" ]; then
  if [ -f "$startfile" ]; then
    # the pid will not change when reloading as we use exec, so if the pid is
    # different then we should not run at all since only one instance should run
    # per session.
    file_pid=$(cat "$startfile")
    if [ "$file_pid" -eq "$shed_pid" ]; then
      reloaded="$_true"
    else
      printf '%s\n' "${prog}: instance with pid ${file_pid} already running!"
      exit 1
    fi
  else
    printf '%s\n' "$shed_pid" > "$startfile"
  fi
else
  printf '%s\n' "$shed_pid" > "$startfile"
fi

write_info() {
  printf '%s=%s\n' "VERSION" "$prog_v"
  printf '%s=%s\n' "STARTED" "$(date '+%Y-%m-%d-%H:%M:%S')"
  printf '%s=%s\n' "RUNDIR" "$ShedSessionDir"
}

write_info > "$shed_info"

# write started for when shedc requests a reload
if [ "$reloaded" -eq "$_true" ]; then
  printf '%s\n' "$prog $prog_v started" > "$msg_reply"
fi

if [ "$reloaded" -eq "$_false" ] && ! is_dir_empty "$EnvDir"; then
  for EnvFile in "$EnvDir"/*.env; do
    if [ -r "$EnvFile" ]; then
      msg_log "info" "loading env file $EnvFile"
      . "$EnvFile"
    fi
  done
  unset EnvFile
fi

# Return type: void
#       Usage: wait_exit
# --------------------------------------------------
# this function does not return output whatsoever
# sleep 1 second while the ShedSessionDir exists
wait_exit() {
  while ! is_dir_empty "$ShedSessionDir"; do
    sleep 0.25
  done
}

# Return type: void
#       Usage: daemon_cycle
# --------------------------------------------------
# this function does not return output whatsoever
daemon_cycle() {
  Action=""
  Argument=""
  # daemon cycle to run until we receive a reload action in the socket
  while [ -z "$SHED_RELOAD" ] || [ "$SHED_RELOAD" = 0 ] ; do
    # check that the ShedSessionDir exists
    if [ -d "${ShedSessionDir}" ]; then
      # wait until a write is done to the socket
      # read the contents of the socket, action and argument
      # drain the named pipe $msg_socket
      SocInput=$(cat "$msg_socket")
      # from the socket, first column separated by space
      Action="${SocInput%% *}"
      # from the socket, second column separated by space
      Argument="${SocInput##* }"
      # decide what to do with the read action and argument
      case "${Action}" in
        reload)      SHED_RELOAD=1              ;;
        start)       start_services "$Argument" ;;
        stop)        killprocs "$Argument"      ;;
        hup)         hupprocs "$Argument"       ;;
        wait-logout) wait_exit                  ;;
      esac
    else
      # shed must exit
      SHED_RELOAD=2
    fi
  done
}

# Return type: void
#       Usage: sigHandler "SIG"
# Description:
#   Handle signals to terminate or reload the program
sigHandler () {
  msg_log "received signal $1"
  case "$1" in
    HUP|USR1|USR2)
      printf '%s\n' "reload" > "$msg_socket"
      ;;
    EXIT|TERM|INT|QUIT)
      killprocs "all"
      killcomps "all"
      printf '%s\n' "wait-logout" > "$msg_socket"
      rm -rf "$ShedSessionDir"
      kill "$SHED_SESSION_PID"
      ;;
  esac
}

# start all services on first run
start_str=""
if [ "$reloaded" -eq "$_true" ]; then
  start_str="all"
else
  start_str="firstrun"
fi

msg_log "info" "$prog $prog_v initiated"

if [ "$_true" -eq "$UsingOldShedDir" ]; then
  msg_log "info" "$prog $prog_v using old shed dir $ShedSessionDir"
fi

case "$start_str" in
  "firstrun")
    start_components "$start_str"
    ;;
esac

start_services "$start_str"

trap 'sigHandler "HUP"'  HUP
trap 'sigHandler "USR1"' USR1
trap 'sigHandler "USR2"' USR2
trap 'sigHandler "EXIT"' EXIT
trap 'sigHandler "TERM"' TERM
trap 'sigHandler "INT"'  INT
trap 'sigHandler "QUIT"' QUIT

daemon_cycle

# reload shed
[ "$SHED_RELOAD" = 1 ] && exec shed
