.TH SHED 1 shed\-VERSION
.SH NAME
shed \- Session sHell Execution Daemon
.SH SYNOPSIS
.B shedc
.RB [ \-nph ]
.RB { \fB start | stop | restart | hup \fP }
.IR service | all | reload
.SH DESCRIPTION
shed is a completely init independient implementation of user services
.SH AUTHOR
.EX
eylles                 <ed.ylles1997 at gmail.com>
.EE
.SH HOMEPAGE
.TP
Source code:
.EE
https://codeberg.org/eylles/shed
.EX
