#!/bin/sh

prog="${0##*/}"
mypid="${$}"
# version @VERSION@
prog_v="@VERSION@"

# OldWorkDir=$PWD

# cd "${XDG_CONFIG_HOME}/shed/services"

# result of: id -u $USER
# cuz $UID is not POSIX ¯\_(ツ)_/¯
UserID=$(id -u "$USER")

# dir of the pid files for the current session
GUISessionDir=/run/user/${UserID}/GUISession${GUI_SESSION_PID}

# directory where we are loading the user services to start from
ServicesDir="${XDG_CONFIG_HOME:-${HOME}/.config}/shed/services"

# unix command line compatible booleans

# Type: int
# value: 0
_true=0
# Type: int
# value: 1
_false=1

# read the contents of the pid file, cat but more "elegant"

# Return type: string
#       Usage: read_file file [prefix]
#       [prefix]: if provided the characters here will be used a prefix when
#                 printing the contents of the file.
#      Return: '[prefix]line'
read_file() {
  if [ $# -gt 1 ]; then
    prefix=$2
  else
    prefix=""
  fi
  while read -r FileLine
  do
    printf '%s%s\n' "$prefix" "$FileLine"
  done < "$1"
}

# Return type: string
#       Usage: progspinner prefix [time]
#         prefix: the string the will appear before the progress spinner
#           time: optional, amount of time the spinner will be spinning for,
#                 by default 2 seconds
#      Return: spinner
progspinner() {
  count=0
  spinSymbol=0
  progspinner=0
  progspinnerPrefix="$1"
  if [ -z "$2" ]; then
    totaltime=2
  else
    totaltime="$2"
  fi
  steptime=$(awk -v tt="$totaltime" 'BEGIN {printf "%.2f", tt/20}')

  while [ "$count" -le 20 ]; do
    case "$spinSymbol" in
      0) spin="-" ;;
      1) spin="\\" ;;
      2) spin="|" ;;
      3) spin="/" ;;
    esac
    printf ' %s%3d%s\r' "$progspinnerPrefix $spin   [" "$progspinner" "%]"
    sleep "$steptime"
    count=$(( count + 1 ))
    spinSymbol=$(( spinSymbol + 1 ))
    progspinner=$(( progspinner + 5 ))
    [ "$spinSymbol" -gt 3 ] && spinSymbol=0
  done
  printf '  %s%3d%s\r' "$progspinnerPrefix    [" "100" "%]"
  sleep 0.1
  printf '\n'
}

# Return type: string
#       Usage: pretty_print file
# --------------------------------------------------
# uses awk to print the contents of the passed file to the terminal.
pretty_print() {
    awk '
      {
        if (NR==1) {
          printf " ┌"; for(c=0;c<65;c++) printf"─"; printf "┐\n" ;
          printf " │ %63s │\n", $0 ;
          printf " ├"; for(c=0;c<32;c++) printf"─"; printf "┬";
          for(c=0;c<22;c++) printf"─"; printf "┬";
          for(c=0;c<9;c++) printf"─"; printf "┤\n" ;
          printf " │ %30s │ %20s │ %7s │\n", "service           ", "date        ", "status ";
          printf " ├"; for(c=0;c<32;c++) printf"─"; printf "┼";
          for(c=0;c<22;c++) printf"─"; printf "┼";
          for(c=0;c<9;c++) printf"─"; printf "┤\n" ;
          }
        else { printf " │ %30s │ %20s │ %7s │\n", $1, $2, $3 };
      }
      END { printf " └"; for(c=0;c<32;c++) printf"─"; printf "┴";
          for(c=0;c<22;c++) printf"─"; printf "┴";
          for(c=0;c<9;c++) printf"─"; printf "┘\n" ;}
      ' "$1"

}

# Return type: string
#       Usage: read_reply
#      Return: string from called function
# --------------------------------------------------
#  it will read the contents of the reply file and print them to the terminal
#  with either the pretty_print or read_file with "  " as prefix, this is
#  determined by $PrettyPrint being set or not.
read_reply() {
  progspinner "retrieving status:"
  if [ -z "$PrettyPrint" ]; then
    read_file "${GUISessionDir}/reply" "  "
  else
    pretty_print "${GUISessionDir}/reply"
  fi
}

# Return type: string
#       Usage: read_pipe pipe_file
# --------------------------------------------------
# reads the contents of the passed named pipe, will time out in 10 seconds if
# nothing is written to the pipe.
# this is somewhat unreliable in this implementation and needs more work.
read_pipe() {
  # all messages read will be stored here
  varfile="/tmp/${prog}_${mypid}"
  # pipe we read from
  pipe="${1}"
  # we wait max 10 seconds without reply
  waittime=10
  # we cycle twice per second
  cycles=$((waittime * 2))

  cont=0
  while [ "$cont" = 0 ]; do
    : > "$varfile"
    var=""
    cat "$pipe" > "$varfile" &
    catpid=$!
    var=$(cat "$varfile")
    if [ -z "$var" ]; then
      count=0
      while [ "$count" -le "$cycles" ] && [ -z "$var" ]; do
        sleep 0.5
        var=$(cat "$varfile")
        count=$((count + 1))
      done
      kill $catpid 2>/dev/null
    fi
    if [ -z "$var" ]; then
      # echo "timeout: no message received"
      cont=1
    else
      printf '%s\n' "$var"
    fi
  done

  rm "$varfile"
}

# Return type: string
#       Usage: readserviceprop "PROPERTY" service_file
#    property: key name
#      Return: string containing the value of the
#              PROPERTY key from the passed file.
# --------------------------------------------------
# the service files store properties as key=value
# pairs, pass the name of the key to get the stored
# value, valid key names are:
#     NAME
#     EXEC
#     E_ARGS
#     DELAY
#     NOHUP
readserviceprop(){
  # Setting 'IFS' tells 'read' where to split the string.
  while IFS='=' read -r key val; do
    # Skip over lines containing comments.
    # (Lines starting with '#').
    [ "${key##\#*}" ] || continue

    # '$key' stores the key.
    # '$val' stores the value.
    if [ "$key" = "$1" ]; then
      printf '%s\n' "$val"
    fi
  done < "$2"
}

# Return type: string
#       Usage: get_servstatus sfile
#       sfile: full path to the service definition file
get_servstatus() {
  ServiceFile="$1"
  ServiceFileName="${ServiceFile##*/}"
  s_name=""
  s_exec=""
  s_pid=""
  s_state=""
  s_name=$(readserviceprop "NAME" "$ServiceFile")
  s_exec="$(readserviceprop "EXEC" "$ServiceFile")"
  # needed for services that got $HOME/path/service in their EXEC def
  s_exec=$(printf '%s\n' "$s_exec" | sed "s@\$HOME@$HOME@")
  # get the full path of the binary
  s_exec=$(command -v "$s_exec")
  if [ -f "${GUISessionDir}/${s_name}.pid" ]; then
    s_pid=$(read_file "${GUISessionDir}/${s_name}.pid")
    if kill -0 "$s_pid" 2>/dev/null; then
      s_state="+"
    else
      s_state="?"
    fi
  else
      s_state="-"
  fi
  if [ "$PrettyPrint" = 1 ]; then
    printf ' [ %s ] %30s %*s %s\n' "$s_state" "$s_name" "$pw" "$s_pid" "$s_exec"
  else
    printf ' [ %s ] %s\n' "$s_state" "$s_name"
  fi
}

# Return type: string
#       Usage: procstat all | <service name>
#            all: status for all services
# <service name>: status of service
#      Return: status string
# --------------------------------------------------
# for a specific process the status string is:
#   <service name> status: stat
#
# for all processes the information is printed as:
#   [ stat ] <service name>
#
# when PrettyPrint is set the print out is as follows:
#   [ stat ] <service name> pid executable
#
#   stat  |  single proc             |   all procs
#         |  not running             |      -
#         |  running with pid: pid   |      +
#         |  was started             |      ?
procstat() {
  if [ -z "$1" ] || [ "all" = "$1" ]; then
    if [ "$PrettyPrint" = 1 ]; then
      # default pid length
      pw=6
      # use per system pid length
      os_type=$(uname -s)
      case "${os_type}" in
        Linux)
          pw=$(wc -c /proc/sys/kernel/pid_max | awk '{ print $1 }')
          ;;
        NetBSD)
          pidmax=30000
          pw=$(printf '%s\n' "$pidmax" | wc -c)
          ;;
        OpenBSD|FreeBSD|*BSD)
          pidmax=99999
          pw=$(printf '%s\n' "$pidmax" | wc -c)
          ;;
      esac
    fi
    for i in "${ServicesDir}"/* ; do
      get_servstatus "$i"
    done
  else
    for i in "${ServicesDir}"/* ; do
      ServiceFileName="${i##*/}"
      if [ "$ServiceFileName" = "$1" ]; then
        get_servstatus "$i"
      fi
    done
  fi
}

# Return type: string
#       Usage: hupprocs all | <service name>
#            all: hup to all services
# <service name>: service to hup
# --------------------------------------------------
# prints to terminal
hupprocs() {
  if [ -z "$1" ] || [ "all" = "$1" ]; then
    for i in "${GUISessionDir}"/*.pid ; do
      s_pid=$(read_file "$i")
      # s_name=$(ps -p "$s_pid" -o comm=)
      s_name="${i##*/}"
      for s in "${ServicesDir}"/* ; do
        ServiceFileName="${s##*/}"
        i_name=$(readserviceprop "NAME" "$s")
        if [ "$s_name" = "$i_name" ]; then
          s_nohup=$(readserviceprop "NOHUP" "$s")
        fi
      done
      if [ -z "$s_nohup" ]; then
        canhup="$_true"
      else
        case "$s_nohup" in
          true|TRUE|1|yes|YES|y|Y)
            canhup="$_false"
            ;;
          *)
            canhup="$_true"
            ;;
        esac
      fi
      if [ "$canhup" -eq "$_false" ]; then
        printf 'cannot hup service %s\n' "$s_name"
      else
        printf ' sending hup to %s\t%s\n' "$s_pid" "$s_name"
        if kill -0 "$s_pid" 2>/dev/null; then
          [ -z "$dry_run" ] && kill -HUP "$s_pid"
        fi
      fi
    done
  else
    for i in "${ServicesDir}"/* ; do
      ServiceFileName="${i##*/}"
      if [ "$ServiceFileName" = "$1" ]; then
        s_name=$(readserviceprop "NAME" "$i")
        s_nohup=$(readserviceprop "NOHUP" "$i")
        if [ -z "$s_nohup" ]; then
          canhup="$_true"
        else
          case "$s_nohup" in
            true|TRUE|1|yes|YES|y|Y)
              canhup="$_false"
              ;;
            *)
              canhup="$_true"
              ;;
          esac
        fi
        if [ "$canhup" -eq "$_false" ]; then
          printf 'cannot hup service %s\n' "$s_name"
        else
          if [ -f "${GUISessionDir}/${s_name}.pid" ]; then
            s_pid=$(read_file "${GUISessionDir}/${s_name}.pid")
            printf ' sending hup to %s\t%s\n' "$s_pid" "$s_name"
            if kill -0 "$s_pid" 2>/dev/null; then
              [ -z "$dry_run" ] && kill -HUP "$s_pid"
            fi
          else
            printf 'service %s not running\n' "$s_name"
          fi
        fi
      fi
    done
  fi
}

# Return type: string
#       Usage: killchilds all | <service name>
#            all: hup to all services
# <service name>: service to kill
# --------------------------------------------------
# prints to terminal
killchilds() {
  if [ -z "$1" ] || [ "all" = "$1" ]; then
    for i in "${GUISessionDir}"/*.pid ; do
      s_pid=$(read_file "$i")
      # s_name=$(ps -p "$s_pid" -o comm=)
      s_name="${i##*/}"
      printf ' sending term to %s\t%s\n' "$s_pid" "$s_name"
      if kill -0 "$s_pid" 2>/dev/null; then
      [ -z "$dry_run" ] && kill "$s_pid"
      fi
      [ -z "$dry_run" ] && rm -f "$i"
    done
  else
    for i in "${ServicesDir}"/* ; do
      ServiceFileName="${i##*/}"
      if [ "$ServiceFileName" = "$1" ]; then
        s_name=$(readserviceprop "NAME" "$i")
        if [ -f "${GUISessionDir}/${s_name}.pid" ]; then
          s_pid=$(read_file "${GUISessionDir}/${s_name}.pid")
          printf ' sending term to %s\t%s\n' "$s_pid" "$s_name"
          if kill -0 "$s_pid" 2>/dev/null; then
          [ -z "$dry_run" ] && kill "$s_pid"
          fi
          [ -z "$dry_run" ] && rm -f "${GUISessionDir}/${s_name}.pid"
        else
          printf 'service %s not running\n' "$s_name"
        fi
      fi
    done
  fi
}

# Return type: void
#       Usage: daemon_send <action> all | <service name>
#       <action>: hup, stop, start, reload
#            all: apply action to all services
# <service name>: service to perform action on
# --------------------------------------------------
# sends requests to the shed daemon
daemon_send() {
  printf '%s %s\n' "$1" "$2" > "${GUISessionDir}/socket"
}

# Return type: void
#       Usage: kill_session
# --------------------------------------------------
kill_session() {
  killchilds "all"
  [ -z "$dry_run" ] && rm -rf "$GUISessionDir"
  [ -z "$dry_run" ] && kill "$GUI_SESSION_PID"
}

show_version() {
  printf '%s\n' "$prog_v"
}

# Return type: string
#       Usage: show_help
# --------------------------------------------------
# prints to terminal
show_help() {
  printf 'Usage: %s [options] { hup | start | stop | restart | status } [service name] | reload | logout \n' "$prog"
  printf '  -n        dry run.\n  -h        show this help.\n'
  printf '  -V        show version.\n'
  printf '  -p        pretty print reply.\n'
  printf '   hup      send hup to the session service(s)\n'
  printf '   stop     send term to the session service(s)\n'
  printf '   start    send request to start the session service(s)\n'
  printf '   restart  send term to the session service(s) and then send request to start the service(s)\n'
  printf '   logout   send term to the session services and the xsession process\n'
  printf '   reload   send term to the session services and reload shed\n'
  printf '   status   shows the status of the desired service'
  printf 'for all services the status is shown with a symbol as follows:\n'
  printf '\t     [ + ] means the service is running\n'
  printf '\t     [ - ] means the service is not running\n'
  printf '\t     [ ? ] means the service was started but the pid was not among the active processes\n'
}

OPTIND=1
while getopts nhpV o; do case "${o}" in
  h) help=1 ;;
  n) dry_run=1 ;;
  p) PrettyPrint=1 ;;
  V) version=1 ;;
  *) help=1 ;;
esac done
shift $(( OPTIND - 1 ))

[ -z "$invalid" ] || { show_help ; exit 1 ;}
[ -z "$help" ] || { show_help ; exit; }
[ -z "$version" ] || { show_version ; exit; }
case $1 in
  stop)
    killchilds "$2"
  ;;
  restart)
    killchilds "$2"
    progspinner "restarting service(s)" 1
    daemon_send "start" "$2"
    read_reply
  ;;
  hup)
    hupprocs "$2"
  ;;
  status)
    procstat "$2"
  ;;
  start)
    daemon_send "start" "$2"
    read_reply
  ;;
  logout)
    kill_session
  ;;
  reload)
    killchilds "all"
    progspinner "reloading shed" 2
    daemon_send "reload"
    read_reply
  ;;
  *) show_help ; exit 1 ;;
esac

# cd "$OldWorkDir"
